// Builds src/core/service-catalog.ts from the awg-manager preset catalog
// (internal/presets/defaults.json, MIT). Keeps only presets that carry domain
// lists — sing-box .srs rule-sets have no meaning for WireGuard/Clash here.
//
//   node scripts/build-catalog.mjs [path/to/defaults.json]
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = process.argv[2];
if (!src) {
  console.error("usage: node scripts/build-catalog.mjs <defaults.json>");
  process.exit(1);
}

const raw = JSON.parse(readFileSync(src, "utf8"));
const list = Array.isArray(raw) ? raw : (raw.presets ?? raw.data ?? []);

const CATEGORY_LABELS = {
  ai: "AI",
  block: "Блокировки",
  cloud: "Облака и сервисы",
  developer: "Разработка",
  gaming: "Игры",
  media: "Медиа",
  social: "Соцсети и мессенджеры",
};

const entries = [];
for (const p of list) {
  const domains = p?.engines?.dns?.domains;
  if (!Array.isArray(domains) || !domains.length) continue;
  const clean = [...new Set(domains.map((d) => String(d).trim().toLowerCase()).filter(Boolean))].sort();
  entries.push({
    id: String(p.id),
    name: String(p.name ?? p.id),
    category: String(p.category ?? "other"),
    domains: clean,
  });
}
entries.sort((a, b) => a.category.localeCompare(b.category) || a.id.localeCompare(b.id));

const totalDomains = entries.reduce((s, e) => s + e.domains.length, 0);

const out = [
  "// AUTO-GENERATED by scripts/build-catalog.mjs — do not edit by hand.",
  "//",
  "// Service catalog from hoaxisr/awg-manager (internal/presets/defaults.json, MIT):",
  `// ${entries.length} services, ${totalDomains} domains. Used for split tunneling`,
  "// (domains resolved via DoH) and for Clash routing rules (DOMAIN-SUFFIX).",
  "",
  "export interface CatalogService {",
  "  id: string;",
  "  name: string;",
  "  category: string;",
  "  domains: string[];",
  "}",
  "",
  `export const CATEGORY_LABELS: Record<string, string> = ${JSON.stringify(CATEGORY_LABELS, null, 2)};`,
  "",
  "export const SERVICE_CATALOG: CatalogService[] = [",
  ...entries.map((e) => `  ${JSON.stringify(e)},`),
  "];",
  "",
  "/** Services grouped by category, for a grouped picker. */",
  "export function catalogByCategory(): Array<{ category: string; label: string; services: CatalogService[] }> {",
  "  const map = new Map<string, CatalogService[]>();",
  "  for (const s of SERVICE_CATALOG) {",
  "    const list = map.get(s.category) ?? [];",
  "    list.push(s);",
  "    map.set(s.category, list);",
  "  }",
  "  return [...map.entries()]",
  "    .map(([category, services]) => ({ category, label: CATEGORY_LABELS[category] ?? category, services }))",
  "    .sort((a, b) => a.label.localeCompare(b.label));",
  "}",
  "",
  "/** Merged, de-duplicated domain list for the selected service ids. */",
  "export function domainsForServices(ids: string[]): string[] {",
  "  const want = new Set(ids);",
  "  const out = new Set<string>();",
  "  for (const s of SERVICE_CATALOG) {",
  "    if (!want.has(s.id)) continue;",
  "    for (const d of s.domains) out.add(d);",
  "  }",
  "  return [...out].sort();",
  "}",
  "",
].join("\n");

writeFileSync(join(root, "src/core/service-catalog.ts"), out);
console.log(`wrote src/core/service-catalog.ts — ${entries.length} services, ${totalDomains} domains`);
